name: 'build number'

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_TOKEN }}
        ref: dev
        submodules: true

    # Update references
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"

      
    - name: Set build info
      id: build-info
      run: echo ::set-output name=owner::${{ github.actor }}::set-output name=build-number::${{ github.run_number }}

    - name: Create JSON file
      run: echo "{\"owner\":\"${{ steps.build-info.outputs.owner }}\",\"buildNumber\":\"${{ steps.build-info.outputs.build-number }}\"}" > build-info.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update Build Number in HTML
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { owner, repo, sha } = context;
            
            // Read the HTML file
            const filePath = 'index.html';
            let fileContents = fs.readFileSync(filePath, 'utf8');

            // Extract the build number from the build-info.json
            const buildInfo = JSON.parse(fs.readFileSync('build-info.json', 'utf8'));
            const newBuildNumber = buildInfo.buildNumber;

            // Update the build number in the HTML file
            fileContents = fileContents.replace(/<span id="buildNumber">(\d+)<\/span>/, `<span id="buildNumber">${newBuildNumber}</span>`);

            // Write the updated content back to the HTML file
            fs.writeFileSync(filePath, fileContents);

            // Commit the changes
            await github.rest.repos.createOrUpdateFileContents({
              owner: owner,
              repo: repo,
              path: filePath,
              message: `Update build number to ${newBuildNumber}`,
              content: Buffer.from(fileContents).toString('base64'),
              sha: sha,
            });

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
