<!DOCTYPE html>
<html>
<head>
    <title>Build Number</title>
</head>
<body>
    <h1>Last Build Number</h1>
    <p>
        Owner: <span id="owner"></span><br> 
        Build Number: <span id="buildNumber"></span>
    </p>

    <script>
        // Function to fetch build information from a JSON file
        async function fetchBuildInfo() {
            try {
                const response = await fetch('build-info.json');
                const data = await response.json();

                // Set the owner and build number from the JSON file
                document.getElementById('owner').textContent = data.owner;
                document.getElementById('buildNumber').textContent = data.buildNumber;
            } catch (error) {
                console.error('Error fetching build information:', error);
            }
        }

        // Call the function to fetch build information
        fetchBuildInfo();
    </script>
</body>
</html>
