name: Update Submodule

on:
  workflow_dispatch: # Trigger the workflow manually

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Submodule
      run: |
        # Update the submodule to the latest commit in its repository
        git submodule update --remote

    - name: Commit and Push
      run: |
        # Commit the updated submodule reference
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update submodule reference"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
