name: Update Submodule

on:
  workflow_dispatch: # Trigger the workflow manually

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
         submodules: true

    - name: Update Submodule
      run: |
        tree
        # Update the submodule to the latest commit in its repository
        git submodule update --remote
    - name: Commit and Push
      run: |
        # Commit the updated submodule reference
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update submodule reference"
        git push origin main
      env:
       GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
